/// autogenerated analytical inverse kinematics code from ikfast program part of OpenRAVE
/// \author Rosen Diankov
///
/// Licensed under the Apache License, Version 2.0 (the "License");
/// you may not use this file except in compliance with the License.
/// You may obtain a copy of the License at
///     http://www.apache.org/licenses/LICENSE-2.0
/// 
/// Unless required by applicable law or agreed to in writing, software
/// distributed under the License is distributed on an "AS IS" BASIS,
/// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/// See the License for the specific language governing permissions and
/// limitations under the License.
///
/// ikfast version 0x10000049 generated on 2026-05-17 15:29:21.408239
/// To compile with gcc:
///     gcc -lstdc++ ik.cpp
/// To compile without any main function as a shared object (might need -llapack):
///     gcc -fPIC -lstdc++ -DIKFAST_NO_MAIN -DIKFAST_CLIBRARY -shared -Wl,-soname,libik.so -o libik.so ik.cpp
#define IKFAST_HAS_LIBRARY
#include "ikfast.h" // found inside share/openrave-X.Y/python/ikfast.h
using namespace ikfast;

// check if the included ikfast version matches what this file was compiled with
#define IKFAST_COMPILE_ASSERT(x) extern int __dummy[(int)x]
IKFAST_COMPILE_ASSERT(IKFAST_VERSION==0x10000049);

#include <cmath>
#include <vector>
#include <limits>
#include <algorithm>
#include <complex>

#ifndef IKFAST_ASSERT
#include <stdexcept>
#include <sstream>
#include <iostream>

#ifdef _MSC_VER
#ifndef __PRETTY_FUNCTION__
#define __PRETTY_FUNCTION__ __FUNCDNAME__
#endif
#endif

#ifndef __PRETTY_FUNCTION__
#define __PRETTY_FUNCTION__ __func__
#endif

#define IKFAST_ASSERT(b) { if( !(b) ) { std::stringstream ss; ss << "ikfast exception: " << __FILE__ << ":" << __LINE__ << ": " <<__PRETTY_FUNCTION__ << ": Assertion '" << #b << "' failed"; throw std::runtime_error(ss.str()); } }

#endif

#if defined(_MSC_VER)
#define IKFAST_ALIGNED16(x) __declspec(align(16)) x
#else
#define IKFAST_ALIGNED16(x) x __attribute((aligned(16)))
#endif

#define IK2PI  ((IkReal)6.28318530717959)
#define IKPI  ((IkReal)3.14159265358979)
#define IKPI_2  ((IkReal)1.57079632679490)

#ifdef _MSC_VER
#ifndef isnan
#define isnan _isnan
#endif
#ifndef isinf
#define isinf _isinf
#endif
//#ifndef isfinite
//#define isfinite _isfinite
//#endif
#endif // _MSC_VER

// lapack routines
extern "C" {
  void dgetrf_ (const int* m, const int* n, double* a, const int* lda, int* ipiv, int* info);
  void zgetrf_ (const int* m, const int* n, std::complex<double>* a, const int* lda, int* ipiv, int* info);
  void dgetri_(const int* n, const double* a, const int* lda, int* ipiv, double* work, const int* lwork, int* info);
  void dgesv_ (const int* n, const int* nrhs, double* a, const int* lda, int* ipiv, double* b, const int* ldb, int* info);
  void dgetrs_(const char *trans, const int *n, const int *nrhs, double *a, const int *lda, int *ipiv, double *b, const int *ldb, int *info);
  void dgeev_(const char *jobvl, const char *jobvr, const int *n, double *a, const int *lda, double *wr, double *wi,double *vl, const int *ldvl, double *vr, const int *ldvr, double *work, const int *lwork, int *info);
}

using namespace std; // necessary to get std math routines

#ifdef IKFAST_NAMESPACE
namespace IKFAST_NAMESPACE {
#endif

inline float IKabs(float f) { return fabsf(f); }
inline double IKabs(double f) { return fabs(f); }

inline float IKsqr(float f) { return f*f; }
inline double IKsqr(double f) { return f*f; }

inline float IKlog(float f) { return logf(f); }
inline double IKlog(double f) { return log(f); }

// allows asin and acos to exceed 1. has to be smaller than thresholds used for branch conds and evaluation
#ifndef IKFAST_SINCOS_THRESH
#define IKFAST_SINCOS_THRESH ((IkReal)1e-7)
#endif

// used to check input to atan2 for degenerate cases. has to be smaller than thresholds used for branch conds and evaluation
#ifndef IKFAST_ATAN2_MAGTHRESH
#define IKFAST_ATAN2_MAGTHRESH ((IkReal)1e-7)
#endif

// minimum distance of separate solutions
#ifndef IKFAST_SOLUTION_THRESH
#define IKFAST_SOLUTION_THRESH ((IkReal)1e-6)
#endif

// there are checkpoints in ikfast that are evaluated to make sure they are 0. This threshold speicfies by how much they can deviate
#ifndef IKFAST_EVALCOND_THRESH
#define IKFAST_EVALCOND_THRESH ((IkReal)0.00001)
#endif


inline float IKasin(float f)
{
IKFAST_ASSERT( f > -1-IKFAST_SINCOS_THRESH && f < 1+IKFAST_SINCOS_THRESH ); // any more error implies something is wrong with the solver
if( f <= -1 ) return float(-IKPI_2);
else if( f >= 1 ) return float(IKPI_2);
return asinf(f);
}
inline double IKasin(double f)
{
IKFAST_ASSERT( f > -1-IKFAST_SINCOS_THRESH && f < 1+IKFAST_SINCOS_THRESH ); // any more error implies something is wrong with the solver
if( f <= -1 ) return -IKPI_2;
else if( f >= 1 ) return IKPI_2;
return asin(f);
}

// return positive value in [0,y)
inline float IKfmod(float x, float y)
{
    while(x < 0) {
        x += y;
    }
    return fmodf(x,y);
}

// return positive value in [0,y)
inline double IKfmod(double x, double y)
{
    while(x < 0) {
        x += y;
    }
    return fmod(x,y);
}

inline float IKacos(float f)
{
IKFAST_ASSERT( f > -1-IKFAST_SINCOS_THRESH && f < 1+IKFAST_SINCOS_THRESH ); // any more error implies something is wrong with the solver
if( f <= -1 ) return float(IKPI);
else if( f >= 1 ) return float(0);
return acosf(f);
}
inline double IKacos(double f)
{
IKFAST_ASSERT( f > -1-IKFAST_SINCOS_THRESH && f < 1+IKFAST_SINCOS_THRESH ); // any more error implies something is wrong with the solver
if( f <= -1 ) return IKPI;
else if( f >= 1 ) return 0;
return acos(f);
}
inline float IKsin(float f) { return sinf(f); }
inline double IKsin(double f) { return sin(f); }
inline float IKcos(float f) { return cosf(f); }
inline double IKcos(double f) { return cos(f); }
inline float IKtan(float f) { return tanf(f); }
inline double IKtan(double f) { return tan(f); }
inline float IKsqrt(float f) { if( f <= 0.0f ) return 0.0f; return sqrtf(f); }
inline double IKsqrt(double f) { if( f <= 0.0 ) return 0.0; return sqrt(f); }
inline float IKatan2Simple(float fy, float fx) {
    return atan2f(fy,fx);
}
inline float IKatan2(float fy, float fx) {
    if( isnan(fy) ) {
        IKFAST_ASSERT(!isnan(fx)); // if both are nan, probably wrong value will be returned
        return float(IKPI_2);
    }
    else if( isnan(fx) ) {
        return 0;
    }
    return atan2f(fy,fx);
}
inline double IKatan2Simple(double fy, double fx) {
    return atan2(fy,fx);
}
inline double IKatan2(double fy, double fx) {
    if( isnan(fy) ) {
        IKFAST_ASSERT(!isnan(fx)); // if both are nan, probably wrong value will be returned
        return IKPI_2;
    }
    else if( isnan(fx) ) {
        return 0;
    }
    return atan2(fy,fx);
}

template <typename T>
struct CheckValue
{
    T value;
    bool valid;
};

template <typename T>
inline CheckValue<T> IKatan2WithCheck(T fy, T fx, T epsilon)
{
    CheckValue<T> ret;
    ret.valid = false;
    ret.value = 0;
    if( !isnan(fy) && !isnan(fx) ) {
        if( IKabs(fy) >= IKFAST_ATAN2_MAGTHRESH || IKabs(fx) > IKFAST_ATAN2_MAGTHRESH ) {
            ret.value = IKatan2Simple(fy,fx);
            ret.valid = true;
        }
    }
    return ret;
}

inline float IKsign(float f) {
    if( f > 0 ) {
        return float(1);
    }
    else if( f < 0 ) {
        return float(-1);
    }
    return 0;
}

inline double IKsign(double f) {
    if( f > 0 ) {
        return 1.0;
    }
    else if( f < 0 ) {
        return -1.0;
    }
    return 0;
}

template <typename T>
inline CheckValue<T> IKPowWithIntegerCheck(T f, int n)
{
    CheckValue<T> ret;
    ret.valid = true;
    if( n == 0 ) {
        ret.value = 1.0;
        return ret;
    }
    else if( n == 1 )
    {
        ret.value = f;
        return ret;
    }
    else if( n < 0 )
    {
        if( f == 0 )
        {
            ret.valid = false;
            ret.value = (T)1.0e30;
            return ret;
        }
        if( n == -1 ) {
            ret.value = T(1.0)/f;
            return ret;
        }
    }

    int num = n > 0 ? n : -n;
    if( num == 2 ) {
        ret.value = f*f;
    }
    else if( num == 3 ) {
        ret.value = f*f*f;
    }
    else {
        ret.value = 1.0;
        while(num>0) {
            if( num & 1 ) {
                ret.value *= f;
            }
            num >>= 1;
            f *= f;
        }
    }
    
    if( n < 0 ) {
        ret.value = T(1.0)/ret.value;
    }
    return ret;
}

/// solves the forward kinematics equations.
/// \param pfree is an array specifying the free joints of the chain.
IKFAST_API void ComputeFk(const IkReal* j, IkReal* eetrans, IkReal* eerot) {
IkReal x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18,x19,x20,x21,x22,x23,x24,x25,x26,x27,x28,x29,x30,x31,x32,x33,x34,x35,x36,x37,x38,x39,x40,x41,x42,x43,x44,x45,x46,x47,x48;
x0=IKcos(j[0]);
x1=IKcos(j[1]);
x2=IKsin(j[2]);
x3=IKcos(j[2]);
x4=IKsin(j[1]);
x5=IKsin(j[3]);
x6=IKcos(j[3]);
x7=IKcos(j[5]);
x8=IKsin(j[5]);
x9=IKsin(j[0]);
x10=IKsin(j[4]);
x11=IKcos(j[4]);
x12=((0.39225)*x0);
x13=((1.0)*x6);
x14=((0.09465)*x0);
x15=((1.0)*x5);
x16=((0.09465)*x9);
x17=((0.39225)*x9);
x18=((0.0823)*x5);
x19=((1.0)*x9);
x20=((0.0823)*x6);
x21=((1.0)*x0);
x22=((0.425)*x1);
x23=(x1*x3);
x24=(x10*x9);
x25=(x2*x4);
x26=(x1*x2);
x27=(x3*x4);
x28=(x0*x11);
x29=(x10*x21);
x30=(x21*x25);
x31=(x19*x25);
x32=((((-1.0)*x25))+x23);
x33=(x26+x27);
x34=((((-1.0)*x30))+((x0*x23)));
x35=((((-1.0)*x31))+((x23*x9)));
x36=(x21*(((((-1.0)*x26))+(((-1.0)*x27)))));
x37=(x19*(((((-1.0)*x26))+(((-1.0)*x27)))));
x38=(x34*x6);
x39=(x35*x6);
x40=(x36*x5);
x41=(((x32*x6))+((x5*(((((-1.0)*x26))+(((-1.0)*x27)))))));
x42=((((-1.0)*x13*x33))+(((-1.0)*x15*x32)));
x43=(x38+x40);
x44=(x39+((x37*x5)));
x45=(x11*x43);
x46=(x11*x44);
x47=((((-1.0)*x13*x36))+((x15*(((((-1.0)*x30))+((x21*x23)))))));
x48=(((x5*(((((-1.0)*x31))+(((1.0)*x19*x23))))))+(((-1.0)*x37*x6)));
eerot[0]=(((x47*x8))+((x7*(((((-1.0)*x45))+(((-1.0)*x24)))))));
eerot[1]=(((x47*x7))+((x8*((x45+x24)))));
eerot[2]=(((x10*x43))+(((-1.0)*x11*x19)));
IkReal x49=((1.0)*x14);
eetrans[0]=(((x10*((((x20*x34))+((x18*x36))))))+((x0*x22))+(((-1.0)*x12*x25))+(((-0.10915)*x9))+((x6*(((((-1.0)*x27*x49))+(((-1.0)*x26*x49))))))+((x12*x23))+((x5*(((((-1.0)*x23*x49))+((x14*x25))))))+(((-0.0823)*x11*x9)));
eerot[3]=(((x7*(((((-1.0)*x46))+x29))))+((x48*x8)));
eerot[4]=(((x8*(((((-1.0)*x29))+x46))))+((x48*x7)));
eerot[5]=(((x10*x44))+x28);
IkReal x50=((1.0)*x16);
eetrans[1]=(((x22*x9))+(((0.10915)*x0))+(((-1.0)*x17*x25))+((x5*((((x16*x25))+(((-1.0)*x23*x50))))))+((x17*x23))+(((0.0823)*x28))+((x10*((((x20*x35))+((x18*x37))))))+((x6*(((((-1.0)*x26*x50))+(((-1.0)*x27*x50)))))));
eerot[6]=(((x41*x8))+((x11*x7*((((x32*x5))+((x33*x6)))))));
eerot[7]=(((x41*x7))+((x11*x42*x8)));
eerot[8]=(x10*x42);
eetrans[2]=((0.089159)+(((-0.425)*x4))+((x6*(((((-0.09465)*x23))+(((0.09465)*x25))))))+((x5*(((((0.09465)*x26))+(((0.09465)*x27))))))+(((-0.39225)*x26))+(((-0.39225)*x27))+((x10*(((((-1.0)*x18*x32))+(((-1.0)*x20*x33)))))));
}

IKFAST_API int GetNumFreeParameters() { return 0; }
IKFAST_API int* GetFreeParameters() { return NULL; }
IKFAST_API int GetNumJoints() { return 6; }

IKFAST_API int GetIkRealSize() { return sizeof(IkReal); }

IKFAST_API int GetIkType() { return 0x67000001; }

class IKSolver {
public:
IkReal j7,cj7,sj7,htj7,j7mul,j8,cj8,sj8,htj8,j8mul,j9,cj9,sj9,htj9,j9mul,j10,cj10,sj10,htj10,j10mul,j11,cj11,sj11,htj11,j11mul,j12,cj12,sj12,htj12,j12mul,new_r00,r00,rxp0_0,new_r01,r01,rxp0_1,new_r02,r02,rxp0_2,new_r10,r10,rxp1_0,new_r11,r11,rxp1_1,new_r12,r12,rxp1_2,new_r20,r20,rxp2_0,new_r21,r21,rxp2_1,new_r22,r22,rxp2_2,new_px,px,npx,new_py,py,npy,new_pz,pz,npz,pp;
unsigned char _ij7[2], _nj7,_ij8[2], _nj8,_ij9[2], _nj9,_ij10[2], _nj10,_ij11[2], _nj11,_ij12[2], _nj12;

IkReal j100, cj100, sj100;
unsigned char _ij100[2], _nj100;
bool ComputeIk(const IkReal* eetrans, const IkReal* eerot, const IkReal* pfree, IkSolutionListBase<IkReal>& solutions) {
j7=numeric_limits<IkReal>::quiet_NaN(); _ij7[0] = -1; _ij7[1] = -1; _nj7 = -1; j8=numeric_limits<IkReal>::quiet_NaN(); _ij8[0] = -1; _ij8[1] = -1; _nj8 = -1; j9=numeric_limits<IkReal>::quiet_NaN(); _ij9[0] = -1; _ij9[1] = -1; _nj9 = -1; j10=numeric_limits<IkReal>::quiet_NaN(); _ij10[0] = -1; _ij10[1] = -1; _nj10 = -1; j11=numeric_limits<IkReal>::quiet_NaN(); _ij11[0] = -1; _ij11[1] = -1; _nj11 = -1; j12=numeric_limits<IkReal>::quiet_NaN(); _ij12[0] = -1; _ij12[1] = -1; _nj12 = -1; 
for(int dummyiter = 0; dummyiter < 1; ++dummyiter) {
    solutions.Clear();
r00 = eerot[0*3+0];
r01 = eerot[0*3+1];
r02 = eerot[0*3+2];
r10 = eerot[1*3+0];
r11 = eerot[1*3+1];
r12 = eerot[1*3+2];
r20 = eerot[2*3+0];
r21 = eerot[2*3+1];
r22 = eerot[2*3+2];
px = eetrans[0]; py = eetrans[1]; pz = eetrans[2];

new_r00=((-1.0)*r00);
new_r01=((-1.0)*r01);
new_r02=((-1.0)*r02);
new_px=((((0.0823)*r02))+(((-1.0)*px)));
new_r10=((-1.0)*r10);
new_r11=((-1.0)*r11);
new_r12=((-1.0)*r12);
new_py=((((0.0823)*r12))+(((-1.0)*py)));
new_r20=r20;
new_r21=r21;
new_r22=r22;
new_pz=((-0.089159)+pz+(((-0.0823)*r22)));
r00 = new_r00; r01 = new_r01; r02 = new_r02; r10 = new_r10; r11 = new_r11; r12 = new_r12; r20 = new_r20; r21 = new_r21; r22 = new_r22; px = new_px; py = new_py; pz = new_pz;
IkReal x51=((1.0)*px);
IkReal x52=((1.0)*pz);
IkReal x53=((1.0)*py);
pp=((px*px)+(py*py)+(pz*pz));
npx=(((px*r00))+((py*r10))+((pz*r20)));
npy=(((px*r01))+((py*r11))+((pz*r21)));
npz=(((px*r02))+((py*r12))+((pz*r22)));
rxp0_0=((((-1.0)*r20*x53))+((pz*r10)));
rxp0_1=(((px*r20))+(((-1.0)*r00*x52)));
rxp0_2=((((-1.0)*r10*x51))+((py*r00)));
rxp1_0=((((-1.0)*r21*x53))+((pz*r11)));
rxp1_1=(((px*r21))+(((-1.0)*r01*x52)));
rxp1_2=((((-1.0)*r11*x51))+((py*r01)));
rxp2_0=(((pz*r12))+(((-1.0)*r22*x53)));
rxp2_1=(((px*r22))+(((-1.0)*r02*x52)));
rxp2_2=((((-1.0)*r12*x51))+((py*r02)));
{
IkReal j7eval[2];
j7eval[0]=((px*px)+(py*py));
j7eval[1]=((IKabs(px))+(IKabs(py)));
if( IKabs(j7eval[0]) < 0.0000010000000000  || IKabs(j7eval[1]) < 0.0000010000000000  )
{
continue; // no branches [j7]

} else
{
{
IkReal j7array[2], cj7array[2], sj7array[2];
bool j7valid[2]={false};
_nj7 = 2;
CheckValue<IkReal> x56 = IKatan2WithCheck(IkReal(((-1.0)*py)),IkReal(px),IKFAST_ATAN2_MAGTHRESH);
if(!x56.valid){
continue;
}
IkReal x54=((1.0)*(x56.value));
if((((px*px)+(py*py))) < -0.00001)
continue;
CheckValue<IkReal> x57=IKPowWithIntegerCheck(IKabs(IKsqrt(((px*px)+(py*py)))),-1);
if(!x57.valid){
continue;
}
if( (((0.10915)*(x57.value))) < -1-IKFAST_SINCOS_THRESH || (((0.10915)*(x57.value))) > 1+IKFAST_SINCOS_THRESH )
    continue;
IkReal x55=IKasin(((0.10915)*(x57.value)));
j7array[0]=(x55+(((-1.0)*x54)));
sj7array[0]=IKsin(j7array[0]);
cj7array[0]=IKcos(j7array[0]);
j7array[1]=((3.14159265358979)+(((-1.0)*x54))+(((-1.0)*x55)));
sj7array[1]=IKsin(j7array[1]);
cj7array[1]=IKcos(j7array[1]);
if( j7array[0] > IKPI )
{
    j7array[0]-=IK2PI;
}
else if( j7array[0] < -IKPI )
{    j7array[0]+=IK2PI;
}
j7valid[0] = true;
if( j7array[1] > IKPI )
{
    j7array[1]-=IK2PI;
}
else if( j7array[1] < -IKPI )
{    j7array[1]+=IK2PI;
}
j7valid[1] = true;
for(int ij7 = 0; ij7 < 2; ++ij7)
{
if( !j7valid[ij7] )
{
    continue;
}
_ij7[0] = ij7; _ij7[1] = -1;
for(int iij7 = ij7+1; iij7 < 2; ++iij7)
{
if( j7valid[iij7] && IKabs(cj7array[ij7]-cj7array[iij7]) < IKFAST_SOLUTION_THRESH && IKabs(sj7array[ij7]-sj7array[iij7]) < IKFAST_SOLUTION_THRESH )
{
    j7valid[iij7]=false; _ij7[1] = iij7; break; 
}
}
j7 = j7array[ij7]; cj7 = cj7array[ij7]; sj7 = sj7array[ij7];

{
IkReal j12array[2], cj12array[2], sj12array[2];
bool j12valid[2]={false};
_nj12 = 2;
IkReal x58=cj7*cj7;
IkReal x59=r00*r00;
IkReal x60=r01*r01;
IkReal x61=(r01*sj7);
IkReal x62=((8.0)*cj7);
IkReal x63=(r00*sj7);
IkReal x64=((1.0)*cj7);
IkReal x65=((4.0)*x58);
CheckValue<IkReal> x70=IKPowWithIntegerCheck(((((-1.0)*r11*x64))+x61),-1);
if(!x70.valid){
continue;
}
IkReal x66=x70.value;
IkReal x67=(x63*x66);
CheckValue<IkReal> x71=IKPowWithIntegerCheck(((((-1.0)*cj7*r11))+x61),-1);
if(!x71.valid){
continue;
}
IkReal x68=(r10*x64*(x71.value));
if((((((4.0)*x59))+(((4.0)*x60))+(((-1.0)*r11*x61*x62))+((x65*(r10*r10)))+(((-1.0)*x59*x65))+(((-1.0)*r10*x62*x63))+(((-1.0)*x60*x65))+((x65*(r11*r11))))) < -0.00001)
continue;
IkReal x69=((0.5)*x66*(IKsqrt(((((4.0)*x59))+(((4.0)*x60))+(((-1.0)*r11*x61*x62))+((x65*(r10*r10)))+(((-1.0)*x59*x65))+(((-1.0)*r10*x62*x63))+(((-1.0)*x60*x65))+((x65*(r11*r11)))))));
j12array[0]=((2.0)*(atan((x67+x69+(((-1.0)*x68))))));
sj12array[0]=IKsin(j12array[0]);
cj12array[0]=IKcos(j12array[0]);
j12array[1]=((-2.0)*(atan((x68+x69+(((-1.0)*x67))))));
sj12array[1]=IKsin(j12array[1]);
cj12array[1]=IKcos(j12array[1]);
if( j12array[0] > IKPI )
{
    j12array[0]-=IK2PI;
}
else if( j12array[0] < -IKPI )
{    j12array[0]+=IK2PI;
}
j12valid[0] = true;
if( j12array[1] > IKPI )
{
    j12array[1]-=IK2PI;
}
else if( j12array[1] < -IKPI )
{    j12array[1]+=IK2PI;
}
j12valid[1] = true;
for(int ij12 = 0; ij12 < 2; ++ij12)
{
if( !j12valid[ij12] )
{
    continue;
}
_ij12[0] = ij12; _ij12[1] = -1;
for(int iij12 = ij12+1; iij12 < 2; ++iij12)
{
if( j12valid[iij12] && IKabs(cj12array[ij12]-cj12array[iij12]) < IKFAST_SOLUTION_THRESH && IKabs(sj12array[ij12]-sj12array[iij12]) < IKFAST_SOLUTION_THRESH )
{
    j12valid[iij12]=false; _ij12[1] = iij12; break; 
}
}
j12 = j12array[ij12]; cj12 = cj12array[ij12]; sj12 = sj12array[ij12];
htj12 = IKtan(j12/2);

{
IkReal j9array[2], cj9array[2], sj9array[2];
bool j9valid[2]={false};
_nj9 = 2;
cj9array[0]=((-1.01208011847186)+(((0.567765155775503)*npx*sj12))+(((2.99928766917857)*pp))+(((0.567765155775503)*cj12*npy)));
if( cj9array[0] >= -1-IKFAST_SINCOS_THRESH && cj9array[0] <= 1+IKFAST_SINCOS_THRESH )
{
    j9valid[0] = j9valid[1] = true;
    j9array[0] = IKacos(cj9array[0]);
    sj9array[0] = IKsin(j9array[0]);
    cj9array[1] = cj9array[0];
    j9array[1] = -j9array[0];
    sj9array[1] = -sj9array[0];
}
else if( isnan(cj9array[0]) )
{
    // probably any value will work
    j9valid[0] = true;
    cj9array[0] = 1; sj9array[0] = 0; j9array[0] = 0;
}
for(int ij9 = 0; ij9 < 2; ++ij9)
{
if( !j9valid[ij9] )
{
    continue;
}
_ij9[0] = ij9; _ij9[1] = -1;
for(int iij9 = ij9+1; iij9 < 2; ++iij9)
{
if( j9valid[iij9] && IKabs(cj9array[ij9]-cj9array[iij9]) < IKFAST_SOLUTION_THRESH && IKabs(sj9array[ij9]-sj9array[iij9]) < IKFAST_SOLUTION_THRESH )
{
    j9valid[iij9]=false; _ij9[1] = iij9; break; 
}
}
j9 = j9array[ij9]; cj9 = cj9array[ij9]; sj9 = sj9array[ij9];
{
IkReal evalcond[1];
IkReal x72=(cj12*sj7);
IkReal x73=((0.160905)*npy);
IkReal x74=((0.0804525)*pp);
IkReal x75=(cj7*py);
IkReal x76=(sj12*x74);
IkReal x77=((0.160905)*npx*sj12);
evalcond[0]=((0.0313068546763437)+(((0.03093317821875)*(IKcos(j9))))+((r01*x72*x74))+(((-1.0)*cj12*cj7*r11*x74))+((r00*sj7*x76))+(((-1.0)*px*x72*x73))+(((-0.0927775)*pp))+((cj12*x73*x75))+((x75*x77))+(((-1.0)*cj7*r10*x76))+(((-1.0)*px*sj7*x77)));
if( IKabs(evalcond[0]) > IKFAST_EVALCOND_THRESH  )
{
continue;
}
}

{
IkReal j10eval[2];
j10eval[0]=((-1.00321692348067)+(((-1.0)*cj9)));
j10eval[1]=IKsign(((-1013088.3573)+(((-1009839.78)*cj9))));
if( IKabs(j10eval[0]) < 0.0000010000000000  || IKabs(j10eval[1]) < 0.0000010000000000  )
{
continue; // no branches [j8, j10, j11]

} else
{
{
IkReal j10array[1], cj10array[1], sj10array[1];
bool j10valid[1]={false};
_nj10 = 1;
IkReal x78=((1287240.0)*sj9);
IkReal x79=(cj7*rxp0_1);
IkReal x80=(rxp0_0*sj7);
IkReal x81=((1287240.0)*cj9);
IkReal x82=((1188046.8)*sj12);
IkReal x83=((6800000.0)*pp);
IkReal x84=(cj12*rxp1_0*sj7);
IkReal x85=(sj12*x81);
IkReal x86=(cj12*cj7*rxp1_1);
CheckValue<IkReal> x87=IKPowWithIntegerCheck(IKsign(((-1013088.3573)+(((-1009839.78)*cj9)))),-1);
if(!x87.valid){
continue;
}
CheckValue<IkReal> x88 = IKatan2WithCheck(IkReal(((-2230223.08947)+((x78*x84))+((sj12*x78*x80))+(((-4508927.221)*cj9))+(((-1.0)*x78*x86))+(((-1.0)*sj12*x78*x79))+(((6276000.0)*pp))+((cj9*x83))+(((-2267205.0)*(cj9*cj9))))),IkReal(((((-1.0)*x81*x84))+((x79*x85))+((x79*x82))+(((-2416430.371)*sj9))+((sj9*x83))+(((-1.0)*x80*x85))+(((-1.0)*x80*x82))+(((1188046.8)*x86))+((x81*x86))+(((-1188046.8)*x84))+(((-2267205.0)*cj9*sj9)))),IKFAST_ATAN2_MAGTHRESH);
if(!x88.valid){
continue;
}
j10array[0]=((-1.5707963267949)+(((1.5707963267949)*(x87.value)))+(x88.value));
sj10array[0]=IKsin(j10array[0]);
cj10array[0]=IKcos(j10array[0]);
if( j10array[0] > IKPI )
{
    j10array[0]-=IK2PI;
}
else if( j10array[0] < -IKPI )
{    j10array[0]+=IK2PI;
}
j10valid[0] = true;
for(int ij10 = 0; ij10 < 1; ++ij10)
{
if( !j10valid[ij10] )
{
    continue;
}
_ij10[0] = ij10; _ij10[1] = -1;
for(int iij10 = ij10+1; iij10 < 1; ++iij10)
{
if( j10valid[iij10] && IKabs(cj10array[ij10]-cj10array[iij10]) < IKFAST_SOLUTION_THRESH && IKabs(sj10array[ij10]-sj10array[iij10]) < IKFAST_SOLUTION_THRESH )
{
    j10valid[iij10]=false; _ij10[1] = iij10; break; 
}
}
j10 = j10array[ij10]; cj10 = cj10array[ij10]; sj10 = sj10array[ij10];
{
IkReal evalcond[4];
IkReal x89=IKsin(j10);
IkReal x90=IKcos(j10);
IkReal x91=(sj12*sj7);
IkReal x92=(cj12*npy);
IkReal x93=(cj12*sj7);
IkReal x94=((2.0)*px);
IkReal x95=((1.0)*pp);
IkReal x96=(cj12*cj7);
IkReal x97=(npx*sj12);
IkReal x98=(sj9*x90);
IkReal x99=((1.0)*cj7*sj12);
IkReal x100=(cj9*x89);
IkReal x101=((2.0)*cj7*py);
evalcond[0]=((0.3553574075)+(((-0.0804525)*x100))+(((-0.0804525)*x98))+(((-1.0)*x95))+(((0.3334125)*cj9))+(((-0.074252925)*x89)));
evalcond[1]=((0.09465)+(((-0.425)*x98))+(((-0.39225)*x89))+x92+x97+(((-0.425)*x100)));
evalcond[2]=(((rxp1_0*x93))+(((-0.39225)*x90))+(((-0.425)*cj9*x90))+(((-1.0)*rxp1_1*x96))+((rxp0_0*x91))+(((0.425)*sj9*x89))+(((-1.0)*rxp0_1*x99)));
evalcond[3]=((-0.020662095)+(((-1.0)*r11*x95*x96))+((x101*x92))+((x101*x97))+((pp*r01*x93))+(((0.085628175)*x89))+(((0.0927775)*x98))+(((0.0927775)*x100))+((pp*r00*x91))+(((-1.0)*sj7*x92*x94))+(((-1.0)*npx*x91*x94))+(((-1.0)*cj7*r10*sj12*x95)));
if( IKabs(evalcond[0]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[1]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[2]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[3]) > IKFAST_EVALCOND_THRESH  )
{
continue;
}
}

{
IkReal j8array[1], cj8array[1], sj8array[1];
bool j8valid[1]={false};
_nj8 = 1;
IkReal x102=((9.16170407695831)*sj9);
IkReal x103=(sj10*sj12);
IkReal x104=((9.16170407695831)*cj9);
IkReal x105=(cj10*sj12);
IkReal x106=(cj10*cj12*rxp1_2);
IkReal x107=(cj9*x105);
IkReal x108=((1.0)*r20*sj9);
IkReal x109=(cj10*cj12*r21);
IkReal x110=(cj12*rxp1_2*sj10);
IkReal x111=((1.0)*cj12*r21*sj10);
if( IKabs((((rxp0_2*x104*x105))+(((-1.0)*cj9*x111))+(((-1.0)*sj9*x109))+(((-1.0)*rxp0_2*x102*x103))+((x104*x106))+(((-1.0)*x102*x110))+(((-1.0)*x105*x108))+(((-1.0)*cj9*r20*x103)))) < IKFAST_ATAN2_MAGTHRESH && IKabs((((cj9*x109))+((rxp0_2*x103*x104))+((rxp0_2*x102*x105))+((r20*x107))+((x102*x106))+(((-1.0)*sj9*x111))+((x104*x110))+(((-1.0)*x103*x108)))) < IKFAST_ATAN2_MAGTHRESH && IKabs(IKsqr((((rxp0_2*x104*x105))+(((-1.0)*cj9*x111))+(((-1.0)*sj9*x109))+(((-1.0)*rxp0_2*x102*x103))+((x104*x106))+(((-1.0)*x102*x110))+(((-1.0)*x105*x108))+(((-1.0)*cj9*r20*x103))))+IKsqr((((cj9*x109))+((rxp0_2*x103*x104))+((rxp0_2*x102*x105))+((r20*x107))+((x102*x106))+(((-1.0)*sj9*x111))+((x104*x110))+(((-1.0)*x103*x108))))-1) <= IKFAST_SINCOS_THRESH )
    continue;
j8array[0]=IKatan2((((rxp0_2*x104*x105))+(((-1.0)*cj9*x111))+(((-1.0)*sj9*x109))+(((-1.0)*rxp0_2*x102*x103))+((x104*x106))+(((-1.0)*x102*x110))+(((-1.0)*x105*x108))+(((-1.0)*cj9*r20*x103))), (((cj9*x109))+((rxp0_2*x103*x104))+((rxp0_2*x102*x105))+((r20*x107))+((x102*x106))+(((-1.0)*sj9*x111))+((x104*x110))+(((-1.0)*x103*x108))));
sj8array[0]=IKsin(j8array[0]);
cj8array[0]=IKcos(j8array[0]);
if( j8array[0] > IKPI )
{
    j8array[0]-=IK2PI;
}
else if( j8array[0] < -IKPI )
{    j8array[0]+=IK2PI;
}
j8valid[0] = true;
for(int ij8 = 0; ij8 < 1; ++ij8)
{
if( !j8valid[ij8] )
{
    continue;
}
_ij8[0] = ij8; _ij8[1] = -1;
for(int iij8 = ij8+1; iij8 < 1; ++iij8)
{
if( j8valid[iij8] && IKabs(cj8array[ij8]-cj8array[iij8]) < IKFAST_SOLUTION_THRESH && IKabs(sj8array[ij8]-sj8array[iij8]) < IKFAST_SOLUTION_THRESH )
{
    j8valid[iij8]=false; _ij8[1] = iij8; break; 
}
}
j8 = j8array[ij8]; cj8 = cj8array[ij8]; sj8 = sj8array[ij8];
{
IkReal evalcond[8];
IkReal x112=IKsin(j8);
IkReal x113=IKcos(j8);
IkReal x114=(py*sj7);
IkReal x115=((0.10915)*cj10);
IkReal x116=((0.09465)*sj10);
IkReal x117=((0.3374401625)*cj10);
IkReal x118=(cj7*sj12);
IkReal x119=(cj12*pp);
IkReal x120=(cj7*r01);
IkReal x121=((0.0297200375)*sj10);
IkReal x122=((0.09465)*cj10);
IkReal x123=((0.0238098375)*cj10);
IkReal x124=(pp*sj12);
IkReal x125=(r10*sj7);
IkReal x126=(cj7*px);
IkReal x127=((0.10915)*sj10);
IkReal x128=((0.3334125)*cj10);
IkReal x129=((0.3315299625)*sj10);
IkReal x130=((0.3334125)*sj10);
IkReal x131=((2.0)*npx*sj12);
IkReal x132=(cj12*r11*sj7);
IkReal x133=((2.0)*cj12*npy);
IkReal x134=(cj9*x112);
IkReal x135=(cj9*x113);
IkReal x136=(sj9*x112);
IkReal x137=(sj9*x113);
evalcond[0]=(((cj10*x136))+((r20*sj12))+((sj10*x137))+((sj10*x134))+((cj12*r21))+(((-1.0)*cj10*x135)));
evalcond[1]=(((x127*x136))+(((-1.0)*x115*x134))+(((-1.0)*x115*x137))+((cj12*rxp1_2))+((rxp0_2*sj12))+(((-1.0)*x127*x135)));
evalcond[2]=(((cj10*x134))+((cj10*x137))+((cj12*x120))+x132+(((-1.0)*sj10*x136))+((r00*x118))+((sj10*x135))+((sj12*x125)));
evalcond[3]=(((x127*x137))+((x127*x134))+((cj12*rxp1_1*sj7))+(((-1.0)*x115*x135))+((x115*x136))+((rxp0_1*sj12*sj7))+((rxp0_0*x118))+((cj12*cj7*rxp1_0)));
evalcond[4]=((((-1.0)*x122*x135))+((x122*x136))+(((-1.0)*pz))+((x116*x137))+((x116*x134))+(((-0.39225)*x137))+(((-0.39225)*x134))+(((-0.425)*x112)));
evalcond[5]=((((0.39225)*x136))+((x122*x134))+((x122*x137))+(((-1.0)*x116*x136))+((x116*x135))+(((-0.39225)*x135))+(((-0.425)*x113))+(((-1.0)*x126))+(((-1.0)*x114)));
evalcond[6]=((((-1.0)*x123*x136))+(((-1.0)*x113*x128))+(((0.0804525)*x112))+((x121*x137))+(((-1.0)*pz*x133))+(((-1.0)*pz*x131))+(((0.074252925)*x134))+(((0.074252925)*x137))+(((-1.0)*x112*x130))+(((-1.0)*x117*x135))+((r21*x119))+((r20*x124))+(((-1.0)*x129*x134)));
evalcond[7]=((((-1.0)*x123*x137))+(((0.0804525)*x113))+((x112*x128))+((x117*x134))+(((0.074252925)*x135))+(((-1.0)*x113*x130))+((pp*r00*x118))+(((-1.0)*x126*x133))+((x124*x125))+(((-1.0)*x114*x133))+(((-1.0)*x114*x131))+((r11*sj7*x119))+(((-1.0)*x121*x136))+(((-1.0)*x129*x135))+((x119*x120))+(((-0.074252925)*x136))+(((-2.0)*npx*px*x118)));
if( IKabs(evalcond[0]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[1]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[2]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[3]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[4]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[5]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[6]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[7]) > IKFAST_EVALCOND_THRESH  )
{
continue;
}
}

{
IkReal j11array[1], cj11array[1], sj11array[1];
bool j11valid[1]={false};
_nj11 = 1;
j11array[0]=0;
sj11array[0]=IKsin(j11array[0]);
cj11array[0]=IKcos(j11array[0]);
if( j11array[0] > IKPI )
{
    j11array[0]-=IK2PI;
}
else if( j11array[0] < -IKPI )
{    j11array[0]+=IK2PI;
}
j11valid[0] = true;
for(int ij11 = 0; ij11 < 1; ++ij11)
{
if( !j11valid[ij11] )
{
    continue;
}
_ij11[0] = ij11; _ij11[1] = -1;
for(int iij11 = ij11+1; iij11 < 1; ++iij11)
{
if( j11valid[iij11] && IKabs(cj11array[ij11]-cj11array[iij11]) < IKFAST_SOLUTION_THRESH && IKabs(sj11array[ij11]-sj11array[iij11]) < IKFAST_SOLUTION_THRESH )
{
    j11valid[iij11]=false; _ij11[1] = iij11; break; 
}
}
j11 = j11array[ij11]; cj11 = cj11array[ij11]; sj11 = sj11array[ij11];

{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(6);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j7;
vinfos[0].indices[0] = _ij7[0];
vinfos[0].indices[1] = _ij7[1];
vinfos[0].maxsolutions = _nj7;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j8;
vinfos[1].indices[0] = _ij8[0];
vinfos[1].indices[1] = _ij8[1];
vinfos[1].maxsolutions = _nj8;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j9;
vinfos[2].indices[0] = _ij9[0];
vinfos[2].indices[1] = _ij9[1];
vinfos[2].maxsolutions = _nj9;
vinfos[3].jointtype = 1;
vinfos[3].foffset = j10;
vinfos[3].indices[0] = _ij10[0];
vinfos[3].indices[1] = _ij10[1];
vinfos[3].maxsolutions = _nj10;
vinfos[4].jointtype = 1;
vinfos[4].foffset = j11;
vinfos[4].indices[0] = _ij11[0];
vinfos[4].indices[1] = _ij11[1];
vinfos[4].maxsolutions = _nj11;
vinfos[5].jointtype = 1;
vinfos[5].foffset = j12;
vinfos[5].indices[0] = _ij12[0];
vinfos[5].indices[1] = _ij12[1];
vinfos[5].maxsolutions = _nj12;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
}
}
}
}
}
}

}

}
}
}
}
}
}
}

}

}
}
return solutions.GetNumSolutions()>0;
}
};


/// solves the inverse kinematics equations.
/// \param pfree is an array specifying the free joints of the chain.
IKFAST_API bool ComputeIk(const IkReal* eetrans, const IkReal* eerot, const IkReal* pfree, IkSolutionListBase<IkReal>& solutions) {
IKSolver solver;
return solver.ComputeIk(eetrans,eerot,pfree,solutions);
}

IKFAST_API bool ComputeIk2(const IkReal* eetrans, const IkReal* eerot, const IkReal* pfree, IkSolutionListBase<IkReal>& solutions, void* pOpenRAVEManip) {
IKSolver solver;
return solver.ComputeIk(eetrans,eerot,pfree,solutions);
}

IKFAST_API const char* GetKinematicsHash() { return "<robot:GenericRobot - dual_ur5 (0401ad62d4903033937501fc7ddb8aae)>"; }

IKFAST_API const char* GetIkFastVersion() { return "0x10000049"; }

#ifdef IKFAST_NAMESPACE
} // end namespace
#endif

#ifndef IKFAST_NO_MAIN
#include <stdio.h>
#include <stdlib.h>
#ifdef IKFAST_NAMESPACE
using namespace IKFAST_NAMESPACE;
#endif
int main(int argc, char** argv)
{
    if( argc != 12+GetNumFreeParameters()+1 ) {
        printf("\nUsage: ./ik r00 r01 r02 t0 r10 r11 r12 t1 r20 r21 r22 t2 free0 ...\n\n"
               "Returns the ik solutions given the transformation of the end effector specified by\n"
               "a 3x3 rotation R (rXX), and a 3x1 translation (tX).\n"
               "There are %d free parameters that have to be specified.\n\n",GetNumFreeParameters());
        return 1;
    }

    IkSolutionList<IkReal> solutions;
    std::vector<IkReal> vfree(GetNumFreeParameters());
    IkReal eerot[9],eetrans[3];
    eerot[0] = atof(argv[1]); eerot[1] = atof(argv[2]); eerot[2] = atof(argv[3]); eetrans[0] = atof(argv[4]);
    eerot[3] = atof(argv[5]); eerot[4] = atof(argv[6]); eerot[5] = atof(argv[7]); eetrans[1] = atof(argv[8]);
    eerot[6] = atof(argv[9]); eerot[7] = atof(argv[10]); eerot[8] = atof(argv[11]); eetrans[2] = atof(argv[12]);
    for(std::size_t i = 0; i < vfree.size(); ++i)
        vfree[i] = atof(argv[13+i]);
    bool bSuccess = ComputeIk(eetrans, eerot, vfree.size() > 0 ? &vfree[0] : NULL, solutions);

    if( !bSuccess ) {
        fprintf(stderr,"Failed to get ik solution\n");
        return -1;
    }

    printf("Found %d ik solutions:\n", (int)solutions.GetNumSolutions());
    std::vector<IkReal> solvalues(GetNumJoints());
    for(std::size_t i = 0; i < solutions.GetNumSolutions(); ++i) {
        const IkSolutionBase<IkReal>& sol = solutions.GetSolution(i);
        printf("sol%d (free=%d): ", (int)i, (int)sol.GetFree().size());
        std::vector<IkReal> vsolfree(sol.GetFree().size());
        sol.GetSolution(&solvalues[0],vsolfree.size()>0?&vsolfree[0]:NULL);
        for( std::size_t j = 0; j < solvalues.size(); ++j)
            printf("%.15f, ", solvalues[j]);
        printf("\n");
    }
    return 0;
}

#endif
